### ISSUE TITLE
删除公众号信息会报错

### ISSUE THREAD

**Issue by ArwenMax** [Xavier-Lam/wechat-django#17]
Environment:

Request Method: GET
Request URL: http://localhost/admin/wechat_django/wechatapp/1/delete/

Django Version: 3.1
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wechat_django']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such table: wechat_django_wechatpay) was the direct cause of the following exception:
  File "/home/web/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/web/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/web/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/web/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/web/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/web/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/web/env/lib/python3.8/site-packages/wechat_django/admin/wechatapp.py", line 133, in delete_view
    return super(WeChatAppAdmin, self).delete_view(
  File "/home/web/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/web/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/web/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/web/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1867, in _delete_view
    deleted_objects, model_count, perms_needed, protected = self.get_deleted_objects([obj], request)
  File "/home/web/env/lib/python3.8/site-packages/wechat_django/admin/wechatapp.py", line 202, in get_deleted_objects
    super(WeChatAppAdmin, self).get_deleted_objects(objs, request)
  File "/home/web/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1841, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/web/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 118, in get_deleted_objects
    collector.collect(objs)
  File "/home/web/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 181, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/web/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/web/env/lib/python3.8/site-packages/django/db/models/query.py", line 291, in __bool__
    self._fetch_all()
  File "/home/web/env/lib/python3.8/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/web/env/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/web/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/web/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/web/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /admin/wechat_django/wechatapp/1/delete/
Exception Value: no such table: wechat_django_wechatpay

这是traceback

**Comment by Xavier-Lam** [comment]
installed_app中,是否已加入'wechat_django.pay'.对于微信支付功能需要额外添加该app.

添加后再migrate一下,生成支付相关表

**Comment by ArwenMax** [comment]
我没有安装过pay，也没做过相关设置

**Comment by Xavier-Lam** [comment]
问题已确认 应该是由django 3引起的 要看下怎么处理 如果急用可以暂时先退回django 2版本
