### ISSUE TITLE
支付的订单结果通知失败，提示 Result 表不存在

### ISSUE THREAD

**Issue by JoshYuJump** [Xavier-Lam/wechat-django#8]
支付通知 view 报以下错误：

```bash
WeChat Pay notify server error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wechat_django/pay/models/order.py", line 222, in update
    self.result.update(result, signal=signal, verify=False)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
    self.related.get_accessor_name()
wechat_django.pay.models.order.UnifiedOrder.result.RelatedObjectDoesNotExist: UnifiedOrder has no result.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wechat_django/rest_framework/views.py", line 95, in dispatch
    response = super(APIView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wechat_django/pay/notify.py", line 42, in post
    order.update(data)
  File "/usr/local/lib/python3.6/site-packages/wechat_django/pay/models/order.py", line 228, in update
    obj.update(result, signal=signal, verify=False)
  File "/usr/local/lib/python3.6/site-packages/wechat_django/pay/models/orderresult.py", line 72, in update
    self.save()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
```

从数据库查询 `UnifiedOrderResult` Model 对应的数据表，确实没有生成过数据

**Comment by Xavier-Lam** [comment]
第二个error是什么 只看到traceback 没看到error的类型及信息

**Comment by JoshYuJump** [comment]
```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wechat_django/rest_framework/views.py", line 95, in dispatch
    response = super(APIView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wechat_django/pay/notify.py", line 42, in post
    order.update(data)
  File "/usr/local/lib/python3.6/site-packages/wechat_django/pay/models/order.py", line 228, in update
    obj.update(result, signal=signal, verify=False)
  File "/usr/local/lib/python3.6/site-packages/wechat_django/pay/models/orderresult.py", line 72, in update
    self.save()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1334, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1278, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1278, in <listcomp>
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1277, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1218, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 789, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1430, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/operations.py", line 198, in adapt_datetimefield_value
    raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
```

**Comment by Xavier-Lam** [comment]
尝试在django的settings文件中设置`USE_TZ = True` 另外对于面向国内的项目,建议设置`TIME_ZONE = 'Asia/Shanghai'`

**Comment by JoshYuJump** [comment]
`USE_TZ = True` 默认是关闭的吧
开启系统之前数据库保存的日期可能就不准确了

**Comment by JoshYuJump** [comment]
@Xavier-Lam 如果临时使用以下方案，你觉得可行吗？

修改以下文件的

```bash
/python3.6/site-packages/wechat_django/pay/models/base.py
```

`str2dt` 函数试试，不返回 aware 的时间

```python
    @classmethod
    def str2dt(cls, s):
        if not s:
            return None
        dt = tz.datetime.strptime(s, cls._format)
        return tz.make_aware(dt, cls._tz)
```

修改为

```python
    @classmethod
    def str2dt(cls, s):
        if not s:
            return None
        # dt = tz.datetime.strptime(s, cls._format)
        # return tz.make_aware(dt, cls._tz)
        return datetime.strptime(s, cls._format)
```
